// @vitest-environment node
/**
 * SSR safety suite — renders every major component with react-dom/server in a
 * plain Node environment (no window/document). Any unguarded browser access at
 * render time crashes here, which is exactly what would happen on a Next.js
 * server render. Portals and effects are expected to no-op on the server.
 */
import { describe, it, expect } from 'vitest';
import { renderToString } from 'react-dom/server';
import * as React from 'react';

import {
  BoostProvider,
  ThemeToggle,
  Box,
  Flex,
  Stack,
  Grid,
  Container,
  Section,
  AspectRatio,
  ScrollArea,
  Motion,
  Divider,
  Button,
  IconButton,
  ButtonGroup,
  LinkButton,
  CopyButton,
  FloatingActionButton,
  Input,
  Textarea,
  Select,
  Checkbox,
  Radio,
  RadioGroup,
  Switch,
  FormField,
  SearchInput,
  OTPInput,
  DatePicker,
  TimePicker,
  DateRangePicker,
  FileUpload,
  FileDropzone,
  Alert,
  Badge,
  Tag,
  Chip,
  Avatar,
  AvatarGroup,
  Card,
  Skeleton,
  Spinner,
  Loader,
  ProgressBar,
  EmptyState,
  ErrorState,
  SuccessMessage,
  Snackbar,
  Toast,
  Breadcrumb,
  Pagination,
  Stepper,
  Tabs,
  Accordion,
  BackButton,
  NavLink,
  DropdownMenu,
  Popover,
  Tooltip,
  DataTable,
  Table,
  KPIWidget,
  StatsCard,
  ActivityFeed,
  AreaChart,
  BarChart,
  DonutChart,
  Sparkline,
  Price,
  QuantitySelector,
  StarRating,
  PincodeChecker,
  ProductCard,
  ProductGallery,
  VariantSelector,
  OrderSummary,
  OrderTimeline,
  TrustBadges,
  AssuredBadge,
  LightningDealsBar,
  CartDrawer,
  CouponInput,
  AddToCart,
  StickyAddToCart,
  ReviewBreakdownBars,
  FrequentlyBoughtTogether,
  HeroSection,
  FeatureGrid,
  PricingTable,
  TestimonialCard,
  TestimonialGrid,
  FAQSection,
  LogoCloud,
  CTASection,
  LoginForm,
  RegisterForm,
  ForgotPassword,
  ResetPassword,
  AddressForm,
  Navbar,
  Footer,
  MegaMenu,
  Sidebar,
  MobileBottomNav,
  AnnouncementBar,
  Carousel,
  Modal,
  Drawer,
  BottomSheet,
  ConfirmationDialog,
  CommandPalette,
  NotificationCenter,
  DualMobileActionBar,
  BankOffersAccordion,
} from '../index';

type Case = [string, React.ReactElement];

const chartData = [
  { label: 'Mon', value: 10 },
  { label: 'Tue', value: 30 },
];

const CASES: Case[] = [
  ['BoostProvider', <BoostProvider key="1">children</BoostProvider>],
  ['ThemeToggle', <ThemeToggle key="1" />],
  ['Box', <Box key="1">content</Box>],
  ['Flex', <Flex key="1">content</Flex>],
  ['Stack', <Stack key="1">content</Stack>],
  ['Grid', <Grid key="1">content</Grid>],
  ['Container', <Container key="1">content</Container>],
  ['Section', <Section key="1">content</Section>],
  ['AspectRatio', <AspectRatio key="1">content</AspectRatio>],
  ['ScrollArea', <ScrollArea key="1">content</ScrollArea>],
  ['Motion', <Motion key="1">content</Motion>],
  ['Divider', <Divider key="1" />],
  ['Button', <Button key="1">Buy now</Button>],
  ['IconButton', <IconButton key="1" aria-label="close">x</IconButton>],
  ['ButtonGroup', <ButtonGroup key="1"><Button>A</Button></ButtonGroup>],
  ['LinkButton', <LinkButton key="1" href="/shop">Shop</LinkButton>],
  ['CopyButton', <CopyButton key="1" text="copy me" />],
  ['FloatingActionButton', <FloatingActionButton key="1" aria-label="add">+</FloatingActionButton>],
  ['Input', <Input key="1" label="Email" />],
  ['Textarea', <Textarea key="1" label="Message" />],
  ['Select', <Select key="1" label="Size" options={[{ label: 'S', value: 's' }]} />],
  ['Checkbox', <Checkbox key="1" label="Remember" />],
  ['Radio', <Radio key="1" label="One" name="g" />],
  ['RadioGroup', <RadioGroup key="1" options={[{ label: 'One', value: 1 }]} />],
  ['Switch', <Switch key="1" label="Notifications" />],
  ['FormField', <FormField key="1" label="Field" htmlFor="f"><input id="f" /></FormField>],
  ['SearchInput', <SearchInput key="1" />],
  ['OTPInput', <OTPInput key="1" />],
  ['DatePicker', <DatePicker key="1" label="Date" />],
  ['TimePicker', <TimePicker key="1" label="Time" onChange={() => {}} />],
  ['DateRangePicker', <DateRangePicker key="1" label="Range" />],
  ['FileUpload', <FileUpload key="1" label="Upload" onFilesSelected={() => {}} />],
  ['FileDropzone', <FileDropzone key="1" onFilesSelected={() => {}} />],
  ['Alert', <Alert key="1" title="Watch out">Body</Alert>],
  ['Badge', <Badge key="1">New</Badge>],
  ['Tag', <Tag key="1">Sale</Tag>],
  ['Chip', <Chip key="1" label="Filter" />],
  ['Avatar', <Avatar key="1" name="Aarav Sharma" />],
  ['AvatarGroup', <AvatarGroup key="1"><Avatar name="A B" /><Avatar name="C D" /></AvatarGroup>],
  ['Card', <Card key="1">content</Card>],
  ['Skeleton', <Skeleton key="1" />],
  ['Spinner', <Spinner key="1" />],
  ['Loader', <Loader key="1" />],
  ['ProgressBar', <ProgressBar key="1" value={42} label="Loading" />],
  ['EmptyState', <EmptyState key="1" title="Nothing here" />],
  ['ErrorState', <ErrorState key="1" title="Boom" onRetry={() => {}} />],
  ['SuccessMessage', <SuccessMessage key="1" title="Done" />],
  ['Snackbar', <Snackbar key="1" message="Saved" />],
  ['Toast', <Toast key="1" message="Saved" />],
  ['Breadcrumb', <Breadcrumb key="1" items={[{ label: 'Home', href: '/' }, { label: 'Here' }]} />],
  ['Pagination', <Pagination key="1" currentPage={1} totalPages={5} onPageChange={() => {}} />],
  ['Stepper', <Stepper key="1" steps={[{ id: 'a', label: 'A' }, { id: 'b', label: 'B' }]} activeStep={1} />],
  ['Tabs', <Tabs key="1" items={[{ id: 'a', label: 'A', content: 'CA' }]} />],
  ['Accordion', <Accordion key="1" items={[{ id: 'a', title: 'Q', content: 'Ans' }]} />],
  ['BackButton', <BackButton key="1" />],
  ['NavLink', <NavLink key="1" href="/x">Link</NavLink>],
  ['DropdownMenu', <DropdownMenu key="1" trigger="Actions" items={[{ id: 'a', label: 'Act' }]} />],
  ['Popover', <Popover key="1" trigger="Open" content="Body" />],
  ['Tooltip', <Tooltip key="1" content="Tip"><span>Hover</span></Tooltip>],
  ['DataTable', <DataTable key="1" columns={[{ header: 'Name', key: 'name' }]} data={[{ name: 'X' }]} />],
  ['Table', <Table key="1" columns={[{ header: 'Name', key: 'name' }]} data={[{ name: 'X' }]} />],
  ['KPIWidget', <KPIWidget key="1" title="Revenue" value="$42k" change={12.5} />],
  ['StatsCard', <StatsCard key="1" title="Users" value={1200} />],
  ['ActivityFeed', <ActivityFeed key="1" items={[{ id: '1', user: { name: 'Aarav' }, action: 'placed an order', timestamp: '2m ago' }]} />],
  ['AreaChart', <AreaChart key="1" data={chartData} />],
  ['BarChart', <BarChart key="1" data={chartData} />],
  ['DonutChart', <DonutChart key="1" data={chartData} />],
  ['Sparkline', <Sparkline key="1" data={[1, 2, 3]} />],
  ['Price', <Price key="1" amount={1499} />],
  ['QuantitySelector', <QuantitySelector key="1" value={1} onChange={() => {}} />],
  ['StarRating', <StarRating key="1" rating={4.5} />],
  ['PincodeChecker', <PincodeChecker key="1" />],
  ['ProductCard', <ProductCard key="1" id="p1" title="Shoes" price={2999} />],
  ['ProductGallery', <ProductGallery key="1" images={['a.png']} />],
  ['VariantSelector', <VariantSelector key="1" />],
  ['OrderSummary', <OrderSummary key="1" subtotal={999} />],
  ['OrderTimeline', <OrderTimeline key="1" currentStage="placed" />],
  ['TrustBadges', <TrustBadges key="1" />],
  ['AssuredBadge', <AssuredBadge key="1" />],
  ['LightningDealsBar', <LightningDealsBar key="1" />],
  ['CartDrawer', <CartDrawer key="1" isOpen={false} />],
  ['CouponInput', <CouponInput key="1" />],
  ['AddToCart', <AddToCart key="1" />],
  ['StickyAddToCart', <StickyAddToCart key="1" />],
  ['ReviewBreakdownBars', <ReviewBreakdownBars key="1" breakdown={{ 5: 10, 4: 3 }} />],
  ['FrequentlyBoughtTogether', <FrequentlyBoughtTogether key="1" />],
  ['HeroSection', <HeroSection key="1" title="Ship faster" />],
  ['FeatureGrid', <FeatureGrid key="1" />],
  ['PricingTable', <PricingTable key="1" />],
  ['TestimonialCard', <TestimonialCard key="1" />],
  ['TestimonialGrid', <TestimonialGrid key="1" />],
  ['FAQSection', <FAQSection key="1" />],
  ['LogoCloud', <LogoCloud key="1" />],
  ['CTASection', <CTASection key="1" title="Start" />],
  ['LoginForm', <LoginForm key="1" />],
  ['RegisterForm', <RegisterForm key="1" />],
  ['ForgotPassword', <ForgotPassword key="1" />],
  ['ResetPassword', <ResetPassword key="1" />],
  ['AddressForm', <AddressForm key="1" />],
  ['Navbar', <Navbar key="1" brandName="Boost" />],
  ['Footer', <Footer key="1" brandName="Boost" />],
  ['MegaMenu', <MegaMenu key="1" />],
  ['Sidebar', <Sidebar key="1" />],
  ['MobileBottomNav', <MobileBottomNav key="1" items={[{ id: "home", label: "Home", href: "/" }]} />],
  ['AnnouncementBar', <AnnouncementBar key="1" messages="Free shipping" />],
  ['Carousel', <Carousel key="1" items={[<div key="s1">S1</div>]} />],
  ['Modal', <Modal key="1" isOpen={false} onClose={() => {}}>x</Modal>],
  ['Drawer', <Drawer key="1" isOpen={false} onClose={() => {}}>x</Drawer>],
  ['BottomSheet', <BottomSheet key="1" isOpen={false} onClose={() => {}}>x</BottomSheet>],
  ['ConfirmationDialog', <ConfirmationDialog key="1" isOpen={false} onClose={() => {}} onConfirm={() => {}} title="Delete?" message="Sure?" />],
  ['CommandPalette', <CommandPalette key="1" isOpen={false} onClose={() => {}} />],
  ['NotificationCenter', <NotificationCenter key="1" />],
  ['DualMobileActionBar', <DualMobileActionBar key="1" />],
  ['BankOffersAccordion', <BankOffersAccordion key="1" />],
];

describe('SSR safety (react-dom/server, node environment)', () => {
  it.each(CASES.map(([name, element]) => [name, element] as const))(
    '%s renders on the server without crashing',
    (name, element) => {
      let html: string;
      expect(() => {
        html = renderToString(<BoostProvider>{element}</BoostProvider>);
      }).not.toThrow();
      expect(typeof html!).toBe('string');
      expect(html!.length).toBeGreaterThan(0);
    }
  );

  it('does not access browser globals at module scope', async () => {
    // Importing the index inside Node (this file runs with @vitest-environment node)
    // already proves module-level safety; assert the environment held.
    expect(typeof window).toBe('undefined');
    expect(typeof document).toBe('undefined');
  });
});
